
const mime = require("mime-types");

class StaticFileServer {
  constructor(bundledDir) {
    this.bundledDir = bundledDir;
  }

  async serve(req) {
    const filePath = path.join("/", req.url);
    let currentNode = this.bundledDir;
    let contentType = "application/octet-stream";
    let content;

    const segments = filePath.split("/").filter((s) => s !== "");
    for (const segment of segments) {
      currentNode = currentNode[segment];
      if (!currentNode) {
        throw new Error("Not found");
      }
    }

    if (currentNode.content) {
      content = Buffer.from(currentNode.content, "base64");
      contentType = currentNode.contentType || mime.contentType(path.extname(filePath));
    } else {
      content = JSON.stringify(currentNode);
      contentType = "application/json";
    }

    return {
      status: 200,
      headers: { "Content-Type": contentType },
      body: content,
    };
  }
}

module.exports = new StaticFileServer({"index.html":{"contentType":"text/html; charset=utf-8","content":"PCFET0NUWVBFIGh0bWw+CjxodG1sPgogIDxoZWFkPgogICAgPHRpdGxlPk5lZXRDb2RlPC90aXRsZT4KICAgIDxzdHlsZT4KICAgICAgYm9keSB7CiAgICAgICAgZm9udC1mYW1pbHk6IHNhbnMtc2VyaWY7CiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2Y5ZjlmOTsKICAgICAgICBtYXJnaW46IDA7CiAgICAgICAgcGFkZGluZzogMDsKICAgICAgICBsaW5lLWhlaWdodDogMS41ZW07CiAgICAgIH0KCiAgICAgIC5oZWFkZXIgewogICAgICAgIGJhY2tncm91bmQtY29sb3I6ICMxZjI4MzM7CiAgICAgICAgY29sb3I6ICNmZmZmZmY7CiAgICAgICAgcGFkZGluZzogMWVtOwogICAgICAgIHRleHQtYWxpZ246IGNlbnRlcjsKICAgICAgfQoKICAgICAgLmNvbnRhaW5lciB7CiAgICAgICAgbWFyZ2luOiAyZW0gYXV0bzsKICAgICAgICBwYWRkaW5nOiAyZW07CiAgICAgICAgbWF4LXdpZHRoOiA2NDBweDsKICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmZmZmOwogICAgICAgIGJvcmRlcjogMXB4IHNvbGlkICNlOGU4ZTg7CiAgICAgICAgYm94LXNoYWRvdzogMHB4IDBweCA1cHggcmdiYSgwLCAwLCAwLCAwLjIpOwogICAgICB9CgogICAgICBvbCB7CiAgICAgICAgbGlzdC1zdHlsZS10eXBlOiBub25lOwogICAgICAgIGNvdW50ZXItcmVzZXQ6IGxpc3QtY291bnRlcjsKICAgICAgICBtYXJnaW46IDA7CiAgICAgICAgcGFkZGluZzogMDsKICAgICAgfQoKICAgICAgbGkgewogICAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZTsKICAgICAgICBtYXJnaW46IDAgMCAxZW0gMmVtOwogICAgICAgIHBhZGRpbmc6IDAgMCAwLjBlbSAwZW07CiAgICAgIH0KCiAgICAgIGxpOmJlZm9yZSB7CiAgICAgICAgY29udGVudDogY291bnRlcihsaXN0LWNvdW50ZXIpICIuICI7CiAgICAgICAgY291bnRlci1pbmNyZW1lbnQ6IGxpc3QtY291bnRlcjsKICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgICAgICAgdG9wOiAwOwogICAgICAgIGxlZnQ6IC0xLjVlbTsKICAgICAgICBjb2xvcjogIzFmMjgzMzsKICAgICAgICBmb250LXdlaWdodDogYm9sZDsKICAgICAgfQoKCiAgICAgIGgxIHsKICAgICAgICBmb250LXNpemU6IDIuNWVtOwogICAgICAgIG1hcmdpbjogMDsKICAgICAgfQoKICAgICAgcCB7CiAgICAgICAgbWFyZ2luOiAxZW0gMDsKICAgICAgICBmb250LXNpemU6IDEuMmVtOwogICAgICB9CgogICAgICBhIHsKICAgICAgICBjb2xvcjogIzFmMjgzMzsKICAgICAgICBmb250LXdlaWdodDogYm9sZDsKICAgICAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7CiAgICAgIH0KCiAgICAgIGE6aG92ZXIgewogICAgICAgIHRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOwogICAgICB9CiAgICA8L3N0eWxlPgogIDwvaGVhZD4KICA8Ym9keT4KICAgIDxkaXYgY2xhc3M9ImhlYWRlciI+CiAgICAgIDxoMT5OZWV0Q29kZTwvaDE+CiAgICA8L2Rpdj4KICAgIDxkaXYgY2xhc3M9ImNvbnRhaW5lciI+CiAgICAgIDxwPk5lZXRDb2RlIGlzIGEgcGxhdGZvcm0gZm9yIGRldmVsb3BlcnMgdG8gc2hhcmUgYW5kIGRpc2NvdmVyIHJ1bm5pbmcgY29kZSBhbmQgYXBpcy4gV2hldGhlciB5b3UncmUgYSBiZWdpbm5lciBvciBhbiBleHBlcmllbmNlZCBkZXZlbG9wZXIsIE5lZXRDb2RlIHByb3ZpZGVzIGEgY29tbXVuaXR5LWRyaXZlbiBwbGF0Zm9ybSBmb3IgbGVhcm5pbmcgYW5kIGNvbGxhYm9yYXRpb24uPC9wPgogICAgICA8cD5DaGVjayBvdXQgb3VyIDxhIGhyZWY9Imh0dHBzOi8vZ2l0aHViLmNvbS9maXp4L25lZXQiPkdpdEh1YiByZXBvc2l0b3J5PC9hPiB0byBsZWFybiBtb3JlIGFuZCBnZXQgaW52b2x2ZWQuPC9wPgogICAgICA8cD5UbyB1cGxvYWQgeW91ciBjb2RlIHRvIE5lZXRDb2RlLCBmb2xsb3cgdGhlc2Ugc3RlcHM6PC9wPgogICAgICA8b2w+CiAgICAgICAgPGxpPldyaXRlIGEgPGEgaHJlZj0iaHR0cHM6Ly9naXRodWIuY29tL2ZpengvbmVldC9ibG9iL21haW4vdHlwZXMudHMiPlNlcnZpY2U8L2E+LjwvbGk+CiAgICAgICAgPGxpPkV4cG9ydCBpdCB0byBhIGJ1bmRsZWQgQ29tbW9uSlMgbW9kdWxlLjwvbGk+CiAgICAgICAgPGxpPlVwbG9hZCB5b3VyIGNvZGUgZmlsZSB0byBHaXRIdWIuIEZvciBleGFtcGxlLCBpZiB5b3VyIGNvZGUgaXMgaW4gYSBmaWxlIGNhbGxlZCA8Y29kZT5uZWV0LmpzPC9jb2RlPiBpbiBhIHJlcG9zaXRvcnkgY2FsbGVkIDxjb2RlPmhlbGxvPC9jb2RlPiBvd25lZCBieSA8Y29kZT55b3U8L2NvZGU+LCB0aGUgVVJMIHdvdWxkIGJlOiA8YSBocmVmPSJodHRwczovL2dpdGh1Yi5jb20veW91L2hlbGxvL25lZXQuanMiPmh0dHBzOi8vZ2l0aHViLmNvbS95b3UvaGVsbG8vbmVldC5qczwvYT4uPC9saT4KICAgICAgICA8bGk+T25jZSB5b3VyIGNvZGUgaXMgdXBsb2FkZWQsIHlvdSBjYW4gYWNjZXNzIGl0IG9uIE5lZXRDb2RlIGJ5IHZpc2l0aW5nIHRoZSBjb3JyZXNwb25kaW5nIFVSTDogPGEgaHJlZj0iaHR0cHM6Ly9oZWxsby1uZWV0Lm5lZXRjb2RlLnVzIj5odHRwczovL2hlbGxvLW5lZXQubmVldGNvZGUudXM8L2E+LjwvbGk+CiAgICAgIDwvb2w+CiAgICAgIDxwPk1ha2Ugc3VyZSB0byByZXBsYWNlIHRoZSBleGFtcGxlIDxjb2RlPnlvdTwvY29kZT4sIDxjb2RlPmhlbGxvPC9jb2RlPiwgYW5kIDxjb2RlPm5lZXQuanM8L2NvZGU+IHdpdGggeW91ciBhY3R1YWwgR2l0SHViIHVzZXJuYW1lLCByZXBvc2l0b3J5IG5hbWUsIGFuZCBjb2RlIGZpbGUgbmFtZS48L3A+CgogICAgICA8cD5UaGlzIHBhZ2UgaXMgYWN0dWFsbHkgZHluYW1pY2FsbHkgc2VydmVkIGZyb20gPGEgaHJlZj0iaHR0cHM6Ly9naXRodWIuY29tL2ZpengvbmVldC9ibG9iL21haW4vbmVldC5qcyI+aHR0cHM6Ly9naXRodWIuY29tL2ZpengvbmVldC9ibG9iL21haW4vbmVldC5qczwvYT4uPC9wPgogICAgPC9kaXY+CiAgPC9ib2R5Pgo8L2h0bWw+Cg=="}});
