name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "yarn"
      - run: yarn install
      - run: yarn test
      - run: yarn lint
